export const studioServiceFeaturesOptions = [
  "Experienced",
  "Intermediate",
  "Startup",
  "Skilled",
  "Creative Thinking",
  "Unique Works",
  "24x7 Service",
  "Staff Requirements",
  "High-Quality Equipment",
  "On-Time Delivery",
  "Flexible Scheduling",
  "Last-Minute Booking Available",
  "Professional Team",
  "Dedicated Coordinator",
  "Multi-Camera Setup",
  "Custom Packages",
  "Drone Coverage",
  "Live Streaming",
  "Photo & Video Editing",
  "Lighting Setup",
  "Studio Setup Provided",
];
