export const carCompanies = [
  "Toyota",
  "Honda",
  "Hyundai",
  "Kia",
  "Suzuki",
  "Tata Motors",
  "Mahindra",
  "Volkswagen",
  "Ford",
  "Chevrolet",
  "Nissan",
  "Renault",
  "Skoda",
  "MG (Morris Garages)",
  "Mercedes-Benz",
  "BMW",
  "Audi",
  "Jeep",
  "Lexus",
  "Volvo",
  "Porsche",
  "Jaguar",
  "Land Rover",
  "Fiat",
  "Mini",
  "Isuzu",
  "Mitsubishi",
  "Datsun",
  "Genesis",
  "Bugatti",
  "Ferrari",
  "Lamborghini",
  "Rolls-Royce",
  "Bentley",
  "Citroën",
  "Peugeot",
  "BYD",
  "Tesla",
];


export const transmissions = ["Manual", "Automatic"];
export const fuels = ["Petrol", "Diesel", "CNG", "Hybrid"];
export const seats = ["4" , "5" , "7" , "8" , "10"]
